"""initial

Revision ID: 98d31c6b82eb
Revises: e0261ad7fb7f
Create Date: 2024-04-01 00:16:06.607111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "98d31c6b82eb"
down_revision: Union[str, None] = "e0261ad7fb7f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("points_uuid_key", "points", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("points_uuid_key", "points", ["uuid"])
    # ### end Alembic commands ###
